/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedOrgRouteImport } from './routes/_authed._org'
import { Route as AuthedLayoutRouteImport } from './routes/_authed/layout'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed.onboarding'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AuthedOrgDashboardIndexRouteImport } from './routes/_authed/_org/dashboard/index'
import { Route as AuthedOrgDashboardPlotsRouteImport } from './routes/_authed._org.dashboard.plots'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrgRoute = AuthedOrgRouteImport.update({
  id: '/_org',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLayoutRoute = AuthedLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrgDashboardIndexRoute = AuthedOrgDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedOrgRoute,
} as any)
const AuthedOrgDashboardPlotsRoute = AuthedOrgDashboardPlotsRouteImport.update({
  id: '/dashboard/plots',
  path: '/dashboard/plots',
  getParentRoute: () => AuthedOrgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/layout': typeof AuthedLayoutRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/plots': typeof AuthedOrgDashboardPlotsRoute
  '/dashboard/': typeof AuthedOrgDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/layout': typeof AuthedLayoutRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/plots': typeof AuthedOrgDashboardPlotsRoute
  '/dashboard': typeof AuthedOrgDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/_org': typeof AuthedOrgRouteWithChildren
  '/_authed/layout': typeof AuthedLayoutRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_authed/_org/dashboard/plots': typeof AuthedOrgDashboardPlotsRoute
  '/_authed/_org/dashboard/': typeof AuthedOrgDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/layout'
    | '/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/plots'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/layout'
    | '/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/plots'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/_org'
    | '/_authed/layout'
    | '/_authed/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_authed/_org/dashboard/plots'
    | '/_authed/_org/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_org': {
      id: '/_authed/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedOrgRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/layout': {
      id: '/_authed/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof AuthedLayoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_org/dashboard/': {
      id: '/_authed/_org/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedOrgDashboardIndexRouteImport
      parentRoute: typeof AuthedOrgRoute
    }
    '/_authed/_org/dashboard/plots': {
      id: '/_authed/_org/dashboard/plots'
      path: '/dashboard/plots'
      fullPath: '/dashboard/plots'
      preLoaderRoute: typeof AuthedOrgDashboardPlotsRouteImport
      parentRoute: typeof AuthedOrgRoute
    }
  }
}

interface AuthedOrgRouteChildren {
  AuthedOrgDashboardPlotsRoute: typeof AuthedOrgDashboardPlotsRoute
  AuthedOrgDashboardIndexRoute: typeof AuthedOrgDashboardIndexRoute
}

const AuthedOrgRouteChildren: AuthedOrgRouteChildren = {
  AuthedOrgDashboardPlotsRoute: AuthedOrgDashboardPlotsRoute,
  AuthedOrgDashboardIndexRoute: AuthedOrgDashboardIndexRoute,
}

const AuthedOrgRouteWithChildren = AuthedOrgRoute._addFileChildren(
  AuthedOrgRouteChildren,
)

interface AuthedRouteChildren {
  AuthedOrgRoute: typeof AuthedOrgRouteWithChildren
  AuthedLayoutRoute: typeof AuthedLayoutRoute
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOrgRoute: AuthedOrgRouteWithChildren,
  AuthedLayoutRoute: AuthedLayoutRoute,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
