/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedOrgRouteRouteImport } from './routes/_authed/_org/route'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AuthedOrgFinanceRouteRouteImport } from './routes/_authed/_org/finance/route'
import { Route as AuthedOrgProjectsRouteRouteImport } from './routes/_authed/_org/projects/route'
import { Route as AuthedOrgContactsIndexRouteImport } from './routes/_authed/_org/contacts/index'
import { Route as AuthedOrgDashboardIndexRouteImport } from './routes/_authed/_org/dashboard/index'
import { Route as AuthedOrgFinanceReconciliationRouteImport } from './routes/_authed/_org/finance/reconciliation'
import { Route as AuthedOrgFinanceReminderRouteImport } from './routes/_authed/_org/finance/reminder'
import { Route as AuthedOrgFinanceTransactionsRouteImport } from './routes/_authed/_org/finance/transactions'
import { Route as AuthedOrgMessagingIndexRouteImport } from './routes/_authed/_org/messaging/index'
import { Route as AuthedOrgProjectsPaymentsRouteImport } from './routes/_authed/_org/projects/payments'
import { Route as AuthedOrgProjectsPlotsRouteImport } from './routes/_authed/_org/projects/plots'
import { Route as AuthedOrgProjectsProjectsListRouteImport } from './routes/_authed/_org/projects/projects-list'
import { Route as AuthedOrgSalesIndexRouteImport } from './routes/_authed/_org/sales/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrgRouteRoute = AuthedOrgRouteRouteImport.update({
  id: '/_org',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrgFinanceRouteRoute = AuthedOrgFinanceRouteRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthedOrgRouteRoute,
} as any)
const AuthedOrgProjectsRouteRoute = AuthedOrgProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedOrgRouteRoute,
} as any)
const AuthedOrgContactsIndexRoute = AuthedOrgContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AuthedOrgRouteRoute,
} as any)
const AuthedOrgDashboardIndexRoute = AuthedOrgDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedOrgRouteRoute,
} as any)
const AuthedOrgFinanceReconciliationRoute =
  AuthedOrgFinanceReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthedOrgFinanceRouteRoute,
  } as any)
const AuthedOrgFinanceReminderRoute =
  AuthedOrgFinanceReminderRouteImport.update({
    id: '/reminder',
    path: '/reminder',
    getParentRoute: () => AuthedOrgFinanceRouteRoute,
  } as any)
const AuthedOrgFinanceTransactionsRoute =
  AuthedOrgFinanceTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthedOrgFinanceRouteRoute,
  } as any)
const AuthedOrgMessagingIndexRoute = AuthedOrgMessagingIndexRouteImport.update({
  id: '/messaging/',
  path: '/messaging/',
  getParentRoute: () => AuthedOrgRouteRoute,
} as any)
const AuthedOrgProjectsPaymentsRoute =
  AuthedOrgProjectsPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthedOrgProjectsRouteRoute,
  } as any)
const AuthedOrgProjectsPlotsRoute = AuthedOrgProjectsPlotsRouteImport.update({
  id: '/plots',
  path: '/plots',
  getParentRoute: () => AuthedOrgProjectsRouteRoute,
} as any)
const AuthedOrgProjectsProjectsListRoute =
  AuthedOrgProjectsProjectsListRouteImport.update({
    id: '/projects-list',
    path: '/projects-list',
    getParentRoute: () => AuthedOrgProjectsRouteRoute,
  } as any)
const AuthedOrgSalesIndexRoute = AuthedOrgSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthedOrgRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/finance': typeof AuthedOrgFinanceRouteRouteWithChildren
  '/projects': typeof AuthedOrgProjectsRouteRouteWithChildren
  '/finance/reconciliation': typeof AuthedOrgFinanceReconciliationRoute
  '/finance/reminder': typeof AuthedOrgFinanceReminderRoute
  '/finance/transactions': typeof AuthedOrgFinanceTransactionsRoute
  '/projects/payments': typeof AuthedOrgProjectsPaymentsRoute
  '/projects/plots': typeof AuthedOrgProjectsPlotsRoute
  '/projects/projects-list': typeof AuthedOrgProjectsProjectsListRoute
  '/contacts/': typeof AuthedOrgContactsIndexRoute
  '/dashboard/': typeof AuthedOrgDashboardIndexRoute
  '/messaging/': typeof AuthedOrgMessagingIndexRoute
  '/sales/': typeof AuthedOrgSalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/finance': typeof AuthedOrgFinanceRouteRouteWithChildren
  '/projects': typeof AuthedOrgProjectsRouteRouteWithChildren
  '/finance/reconciliation': typeof AuthedOrgFinanceReconciliationRoute
  '/finance/reminder': typeof AuthedOrgFinanceReminderRoute
  '/finance/transactions': typeof AuthedOrgFinanceTransactionsRoute
  '/projects/payments': typeof AuthedOrgProjectsPaymentsRoute
  '/projects/plots': typeof AuthedOrgProjectsPlotsRoute
  '/projects/projects-list': typeof AuthedOrgProjectsProjectsListRoute
  '/contacts': typeof AuthedOrgContactsIndexRoute
  '/dashboard': typeof AuthedOrgDashboardIndexRoute
  '/messaging': typeof AuthedOrgMessagingIndexRoute
  '/sales': typeof AuthedOrgSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_authed/_org': typeof AuthedOrgRouteRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_authed/_org/finance': typeof AuthedOrgFinanceRouteRouteWithChildren
  '/_authed/_org/projects': typeof AuthedOrgProjectsRouteRouteWithChildren
  '/_authed/_org/finance/reconciliation': typeof AuthedOrgFinanceReconciliationRoute
  '/_authed/_org/finance/reminder': typeof AuthedOrgFinanceReminderRoute
  '/_authed/_org/finance/transactions': typeof AuthedOrgFinanceTransactionsRoute
  '/_authed/_org/projects/payments': typeof AuthedOrgProjectsPaymentsRoute
  '/_authed/_org/projects/plots': typeof AuthedOrgProjectsPlotsRoute
  '/_authed/_org/projects/projects-list': typeof AuthedOrgProjectsProjectsListRoute
  '/_authed/_org/contacts/': typeof AuthedOrgContactsIndexRoute
  '/_authed/_org/dashboard/': typeof AuthedOrgDashboardIndexRoute
  '/_authed/_org/messaging/': typeof AuthedOrgMessagingIndexRoute
  '/_authed/_org/sales/': typeof AuthedOrgSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/finance'
    | '/projects'
    | '/finance/reconciliation'
    | '/finance/reminder'
    | '/finance/transactions'
    | '/projects/payments'
    | '/projects/plots'
    | '/projects/projects-list'
    | '/contacts/'
    | '/dashboard/'
    | '/messaging/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/finance'
    | '/projects'
    | '/finance/reconciliation'
    | '/finance/reminder'
    | '/finance/transactions'
    | '/projects/payments'
    | '/projects/plots'
    | '/projects/projects-list'
    | '/contacts'
    | '/dashboard'
    | '/messaging'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/_org'
    | '/_authed/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_authed/_org/finance'
    | '/_authed/_org/projects'
    | '/_authed/_org/finance/reconciliation'
    | '/_authed/_org/finance/reminder'
    | '/_authed/_org/finance/transactions'
    | '/_authed/_org/projects/payments'
    | '/_authed/_org/projects/plots'
    | '/_authed/_org/projects/projects-list'
    | '/_authed/_org/contacts/'
    | '/_authed/_org/dashboard/'
    | '/_authed/_org/messaging/'
    | '/_authed/_org/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_org': {
      id: '/_authed/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedOrgRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_org/finance': {
      id: '/_authed/_org/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthedOrgFinanceRouteRouteImport
      parentRoute: typeof AuthedOrgRouteRoute
    }
    '/_authed/_org/projects': {
      id: '/_authed/_org/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthedOrgProjectsRouteRouteImport
      parentRoute: typeof AuthedOrgRouteRoute
    }
    '/_authed/_org/contacts/': {
      id: '/_authed/_org/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthedOrgContactsIndexRouteImport
      parentRoute: typeof AuthedOrgRouteRoute
    }
    '/_authed/_org/dashboard/': {
      id: '/_authed/_org/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedOrgDashboardIndexRouteImport
      parentRoute: typeof AuthedOrgRouteRoute
    }
    '/_authed/_org/finance/reconciliation': {
      id: '/_authed/_org/finance/reconciliation'
      path: '/reconciliation'
      fullPath: '/finance/reconciliation'
      preLoaderRoute: typeof AuthedOrgFinanceReconciliationRouteImport
      parentRoute: typeof AuthedOrgFinanceRouteRoute
    }
    '/_authed/_org/finance/reminder': {
      id: '/_authed/_org/finance/reminder'
      path: '/reminder'
      fullPath: '/finance/reminder'
      preLoaderRoute: typeof AuthedOrgFinanceReminderRouteImport
      parentRoute: typeof AuthedOrgFinanceRouteRoute
    }
    '/_authed/_org/finance/transactions': {
      id: '/_authed/_org/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof AuthedOrgFinanceTransactionsRouteImport
      parentRoute: typeof AuthedOrgFinanceRouteRoute
    }
    '/_authed/_org/messaging/': {
      id: '/_authed/_org/messaging/'
      path: '/messaging'
      fullPath: '/messaging/'
      preLoaderRoute: typeof AuthedOrgMessagingIndexRouteImport
      parentRoute: typeof AuthedOrgRouteRoute
    }
    '/_authed/_org/projects/payments': {
      id: '/_authed/_org/projects/payments'
      path: '/payments'
      fullPath: '/projects/payments'
      preLoaderRoute: typeof AuthedOrgProjectsPaymentsRouteImport
      parentRoute: typeof AuthedOrgProjectsRouteRoute
    }
    '/_authed/_org/projects/plots': {
      id: '/_authed/_org/projects/plots'
      path: '/plots'
      fullPath: '/projects/plots'
      preLoaderRoute: typeof AuthedOrgProjectsPlotsRouteImport
      parentRoute: typeof AuthedOrgProjectsRouteRoute
    }
    '/_authed/_org/projects/projects-list': {
      id: '/_authed/_org/projects/projects-list'
      path: '/projects-list'
      fullPath: '/projects/projects-list'
      preLoaderRoute: typeof AuthedOrgProjectsProjectsListRouteImport
      parentRoute: typeof AuthedOrgProjectsRouteRoute
    }
    '/_authed/_org/sales/': {
      id: '/_authed/_org/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthedOrgSalesIndexRouteImport
      parentRoute: typeof AuthedOrgRouteRoute
    }
  }
}

interface AuthedOrgFinanceRouteRouteChildren {
  AuthedOrgFinanceReconciliationRoute: typeof AuthedOrgFinanceReconciliationRoute
  AuthedOrgFinanceReminderRoute: typeof AuthedOrgFinanceReminderRoute
  AuthedOrgFinanceTransactionsRoute: typeof AuthedOrgFinanceTransactionsRoute
}

const AuthedOrgFinanceRouteRouteChildren: AuthedOrgFinanceRouteRouteChildren = {
  AuthedOrgFinanceReconciliationRoute: AuthedOrgFinanceReconciliationRoute,
  AuthedOrgFinanceReminderRoute: AuthedOrgFinanceReminderRoute,
  AuthedOrgFinanceTransactionsRoute: AuthedOrgFinanceTransactionsRoute,
}

const AuthedOrgFinanceRouteRouteWithChildren =
  AuthedOrgFinanceRouteRoute._addFileChildren(
    AuthedOrgFinanceRouteRouteChildren,
  )

interface AuthedOrgProjectsRouteRouteChildren {
  AuthedOrgProjectsPaymentsRoute: typeof AuthedOrgProjectsPaymentsRoute
  AuthedOrgProjectsPlotsRoute: typeof AuthedOrgProjectsPlotsRoute
  AuthedOrgProjectsProjectsListRoute: typeof AuthedOrgProjectsProjectsListRoute
}

const AuthedOrgProjectsRouteRouteChildren: AuthedOrgProjectsRouteRouteChildren =
  {
    AuthedOrgProjectsPaymentsRoute: AuthedOrgProjectsPaymentsRoute,
    AuthedOrgProjectsPlotsRoute: AuthedOrgProjectsPlotsRoute,
    AuthedOrgProjectsProjectsListRoute: AuthedOrgProjectsProjectsListRoute,
  }

const AuthedOrgProjectsRouteRouteWithChildren =
  AuthedOrgProjectsRouteRoute._addFileChildren(
    AuthedOrgProjectsRouteRouteChildren,
  )

interface AuthedOrgRouteRouteChildren {
  AuthedOrgFinanceRouteRoute: typeof AuthedOrgFinanceRouteRouteWithChildren
  AuthedOrgProjectsRouteRoute: typeof AuthedOrgProjectsRouteRouteWithChildren
  AuthedOrgContactsIndexRoute: typeof AuthedOrgContactsIndexRoute
  AuthedOrgDashboardIndexRoute: typeof AuthedOrgDashboardIndexRoute
  AuthedOrgMessagingIndexRoute: typeof AuthedOrgMessagingIndexRoute
  AuthedOrgSalesIndexRoute: typeof AuthedOrgSalesIndexRoute
}

const AuthedOrgRouteRouteChildren: AuthedOrgRouteRouteChildren = {
  AuthedOrgFinanceRouteRoute: AuthedOrgFinanceRouteRouteWithChildren,
  AuthedOrgProjectsRouteRoute: AuthedOrgProjectsRouteRouteWithChildren,
  AuthedOrgContactsIndexRoute: AuthedOrgContactsIndexRoute,
  AuthedOrgDashboardIndexRoute: AuthedOrgDashboardIndexRoute,
  AuthedOrgMessagingIndexRoute: AuthedOrgMessagingIndexRoute,
  AuthedOrgSalesIndexRoute: AuthedOrgSalesIndexRoute,
}

const AuthedOrgRouteRouteWithChildren = AuthedOrgRouteRoute._addFileChildren(
  AuthedOrgRouteRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedOrgRouteRoute: typeof AuthedOrgRouteRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedOrgRouteRoute: AuthedOrgRouteRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
