/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedOrgRouteRouteImport } from './routes/_authed/_org/route'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AuthedOrgDashboardIndexRouteImport } from './routes/_authed/_org/dashboard/index'
import { Route as AuthedOrgDashboardPlotsRouteImport } from './routes/_authed/_org/dashboard/plots'
import { Route as AuthedOrgFinanceIndexRouteImport } from './routes/_authed/_org/finance/index'
import { Route as AuthedOrgFinanceTransactionsRouteImport } from './routes/_authed/_org/finance/transactions'
import { Route as AuthedOrgMessagingIndexRouteImport } from './routes/_authed/_org/messaging/index'
import { Route as AuthedOrgProjectsIndexRouteImport } from './routes/_authed/_org/projects/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrgRouteRoute = AuthedOrgRouteRouteImport.update({
  id: '/_org',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrgDashboardIndexRoute = AuthedOrgDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedOrgRouteRoute,
} as any)
const AuthedOrgDashboardPlotsRoute = AuthedOrgDashboardPlotsRouteImport.update({
  id: '/dashboard/plots',
  path: '/dashboard/plots',
  getParentRoute: () => AuthedOrgRouteRoute,
} as any)
const AuthedOrgFinanceIndexRoute = AuthedOrgFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AuthedOrgRouteRoute,
} as any)
const AuthedOrgFinanceTransactionsRoute =
  AuthedOrgFinanceTransactionsRouteImport.update({
    id: '/finance/transactions',
    path: '/finance/transactions',
    getParentRoute: () => AuthedOrgRouteRoute,
  } as any)
const AuthedOrgMessagingIndexRoute = AuthedOrgMessagingIndexRouteImport.update({
  id: '/messaging/',
  path: '/messaging/',
  getParentRoute: () => AuthedOrgRouteRoute,
} as any)
const AuthedOrgProjectsIndexRoute = AuthedOrgProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthedOrgRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/plots': typeof AuthedOrgDashboardPlotsRoute
  '/finance/transactions': typeof AuthedOrgFinanceTransactionsRoute
  '/dashboard/': typeof AuthedOrgDashboardIndexRoute
  '/finance/': typeof AuthedOrgFinanceIndexRoute
  '/messaging/': typeof AuthedOrgMessagingIndexRoute
  '/projects/': typeof AuthedOrgProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/plots': typeof AuthedOrgDashboardPlotsRoute
  '/finance/transactions': typeof AuthedOrgFinanceTransactionsRoute
  '/dashboard': typeof AuthedOrgDashboardIndexRoute
  '/finance': typeof AuthedOrgFinanceIndexRoute
  '/messaging': typeof AuthedOrgMessagingIndexRoute
  '/projects': typeof AuthedOrgProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_authed/_org': typeof AuthedOrgRouteRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_authed/_org/dashboard/plots': typeof AuthedOrgDashboardPlotsRoute
  '/_authed/_org/finance/transactions': typeof AuthedOrgFinanceTransactionsRoute
  '/_authed/_org/dashboard/': typeof AuthedOrgDashboardIndexRoute
  '/_authed/_org/finance/': typeof AuthedOrgFinanceIndexRoute
  '/_authed/_org/messaging/': typeof AuthedOrgMessagingIndexRoute
  '/_authed/_org/projects/': typeof AuthedOrgProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/plots'
    | '/finance/transactions'
    | '/dashboard/'
    | '/finance/'
    | '/messaging/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/plots'
    | '/finance/transactions'
    | '/dashboard'
    | '/finance'
    | '/messaging'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/_org'
    | '/_authed/onboarding'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_authed/_org/dashboard/plots'
    | '/_authed/_org/finance/transactions'
    | '/_authed/_org/dashboard/'
    | '/_authed/_org/finance/'
    | '/_authed/_org/messaging/'
    | '/_authed/_org/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_org': {
      id: '/_authed/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedOrgRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_org/dashboard/': {
      id: '/_authed/_org/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedOrgDashboardIndexRouteImport
      parentRoute: typeof AuthedOrgRouteRoute
    }
    '/_authed/_org/dashboard/plots': {
      id: '/_authed/_org/dashboard/plots'
      path: '/dashboard/plots'
      fullPath: '/dashboard/plots'
      preLoaderRoute: typeof AuthedOrgDashboardPlotsRouteImport
      parentRoute: typeof AuthedOrgRouteRoute
    }
    '/_authed/_org/finance/': {
      id: '/_authed/_org/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthedOrgFinanceIndexRouteImport
      parentRoute: typeof AuthedOrgRouteRoute
    }
    '/_authed/_org/finance/transactions': {
      id: '/_authed/_org/finance/transactions'
      path: '/finance/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof AuthedOrgFinanceTransactionsRouteImport
      parentRoute: typeof AuthedOrgRouteRoute
    }
    '/_authed/_org/messaging/': {
      id: '/_authed/_org/messaging/'
      path: '/messaging'
      fullPath: '/messaging/'
      preLoaderRoute: typeof AuthedOrgMessagingIndexRouteImport
      parentRoute: typeof AuthedOrgRouteRoute
    }
    '/_authed/_org/projects/': {
      id: '/_authed/_org/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthedOrgProjectsIndexRouteImport
      parentRoute: typeof AuthedOrgRouteRoute
    }
  }
}

interface AuthedOrgRouteRouteChildren {
  AuthedOrgDashboardPlotsRoute: typeof AuthedOrgDashboardPlotsRoute
  AuthedOrgFinanceTransactionsRoute: typeof AuthedOrgFinanceTransactionsRoute
  AuthedOrgDashboardIndexRoute: typeof AuthedOrgDashboardIndexRoute
  AuthedOrgFinanceIndexRoute: typeof AuthedOrgFinanceIndexRoute
  AuthedOrgMessagingIndexRoute: typeof AuthedOrgMessagingIndexRoute
  AuthedOrgProjectsIndexRoute: typeof AuthedOrgProjectsIndexRoute
}

const AuthedOrgRouteRouteChildren: AuthedOrgRouteRouteChildren = {
  AuthedOrgDashboardPlotsRoute: AuthedOrgDashboardPlotsRoute,
  AuthedOrgFinanceTransactionsRoute: AuthedOrgFinanceTransactionsRoute,
  AuthedOrgDashboardIndexRoute: AuthedOrgDashboardIndexRoute,
  AuthedOrgFinanceIndexRoute: AuthedOrgFinanceIndexRoute,
  AuthedOrgMessagingIndexRoute: AuthedOrgMessagingIndexRoute,
  AuthedOrgProjectsIndexRoute: AuthedOrgProjectsIndexRoute,
}

const AuthedOrgRouteRouteWithChildren = AuthedOrgRouteRoute._addFileChildren(
  AuthedOrgRouteRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedOrgRouteRoute: typeof AuthedOrgRouteRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedOrgRouteRoute: AuthedOrgRouteRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
